[project]
name = "course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.1",
    "agent-framework>=1.0.0b251028",
    "mcp[cli]>=1.4.1",
]
[tool.uv]
prerelease = "allow"
